### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by XavierCS-dev** [Detrixukaon58/Black-Ice-Engine#2]
Is this project still being worked on, or is it considered abandoned?

**Comment by Detrixukaon58** [comment]
Heya, no this project has not been abandoned. I've just been working on a major overhaul of the rendering system to include more types of shaders. I just want to make sure that I push a version that is able to be built and in its current state on my end, it is not in that state.

**Comment by XavierCS-dev** [comment]
> Heya, no this project has not been abandoned. I've just been working on a major overhaul of the rendering system to include more types of shaders. I just want to make sure that I push a version that is able to be built and in its current state on my end, it is not in that state.

Good luck!
